"""Immutable, authoritative facts for dice generated by the rules engine.

This module records facts supplied by engine resolution code. It deliberately
has no RNG dependency: callers roll exactly once, then append the resulting
faces and decisions to a journal. Participant selectors and browser-facing
presentation belong to the VTT projection layer, not this engine contract.
"""

from __future__ import annotations

import hashlib
import json
import unicodedata
from collections.abc import Sequence
from typing import Annotated, Any, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

ROLL_JOURNAL_SCHEMA_VERSION = "engine.roll_journal.v1"
ROLL_RECORD_SCHEMA_VERSION = "engine.roll_record.v1"

PositiveInt = Annotated[int, Field(strict=True, ge=1)]
DieSides = Annotated[int, Field(strict=True, ge=2)]
NonNegativeInt = Annotated[int, Field(strict=True, ge=0)]


def _canonical_text(value: str, *, field_name: str) -> str:
    if not isinstance(value, str):
        raise TypeError(f"{field_name} must be a string")
    if not value or value != value.strip():
        raise ValueError(f"{field_name} must be non-empty canonical text")
    if any(unicodedata.category(character) == "Cc" for character in value):
        raise ValueError(f"{field_name} must not contain control characters")
    return value


def _tuple_from_wire(value: Any, *, field_name: str) -> tuple[Any, ...]:
    if not isinstance(value, (list, tuple)):
        raise ValueError(f"{field_name} must be an ordered list or tuple")
    return tuple(value)


class RollJournalModel(BaseModel):
    """Strict immutable base for journal records and their nested facts."""

    model_config = ConfigDict(extra="forbid", frozen=True, strict=True)


class RollAudienceIntent(RollJournalModel):
    """Engine visibility intent expressed only in actor terms.

    ``actors`` is projected to participant audiences later, using authoritative
    table ownership. ``gm_only`` represents a blind result without putting a
    participant selector into the rules kernel.
    """

    visibility: Literal["public", "gm_only", "actors"]
    actor_ids: tuple[str, ...]

    @field_validator("actor_ids", mode="before")
    @classmethod
    def validate_actor_ids_shape(cls, value: Any) -> tuple[Any, ...]:
        return _tuple_from_wire(value, field_name="actor_ids")

    @field_validator("actor_ids")
    @classmethod
    def validate_actor_ids(cls, value: tuple[str, ...]) -> tuple[str, ...]:
        actor_ids = tuple(
            _canonical_text(actor_id, field_name="audience actor ID") for actor_id in value
        )
        if len(set(actor_ids)) != len(actor_ids):
            raise ValueError("audience actor IDs must be unique")
        if actor_ids != tuple(sorted(actor_ids)):
            raise ValueError("audience actor IDs must be sorted")
        return actor_ids

    @model_validator(mode="after")
    def validate_visibility(self) -> "RollAudienceIntent":
        if self.visibility == "actors" and not self.actor_ids:
            raise ValueError("actors visibility requires at least one actor ID")
        if self.visibility != "actors" and self.actor_ids:
            raise ValueError(f"actor_ids must be empty for {self.visibility} visibility")
        return self


class DieFace(RollJournalModel):
    """One generated face in generation order, including superseded faces."""

    generation_index: PositiveInt
    sides: DieSides
    value: PositiveInt
    status: Literal["kept", "discarded", "rerolled", "replaced"]
    replacement_generation_index: PositiveInt | None

    @model_validator(mode="after")
    def validate_face(self) -> "DieFace":
        if self.value > self.sides:
            raise ValueError("die value must not exceed its number of sides")
        was_superseded = self.status in {"rerolled", "replaced"}
        if was_superseded != (self.replacement_generation_index is not None):
            raise ValueError(
                "rerolled or replaced faces require a replacement generation index, "
                "and final faces must not have one"
            )
        if (
            self.replacement_generation_index is not None
            and self.replacement_generation_index <= self.generation_index
        ):
            raise ValueError("a replacement generation index must refer to a later face")
        return self


def _validate_generated_faces(faces: tuple[DieFace, ...], *, require_d20: bool) -> None:
    expected = tuple(range(1, len(faces) + 1))
    actual = tuple(face.generation_index for face in faces)
    if actual != expected:
        raise ValueError("die face generation indices must be contiguous and ordered from 1")

    by_generation = {face.generation_index: face for face in faces}
    for face in faces:
        if require_d20 and face.sides != 20:
            raise ValueError("d20 resolutions may contain only twenty-sided faces")
        replacement_index = face.replacement_generation_index
        if replacement_index is None:
            continue
        replacement = by_generation.get(replacement_index)
        if replacement is None:
            raise ValueError("replacement generation index must identify a generated face")
        if replacement.sides != face.sides:
            raise ValueError("a replacement face must use the same number of sides")


class D20Resolution(RollJournalModel):
    """Generated d20 candidates plus the engine's final kept value."""

    expression: str
    mode: Literal["normal", "advantage", "disadvantage"]
    faces: tuple[DieFace, ...]
    candidate_generation_indices: tuple[PositiveInt, ...]
    kept_generation_index: PositiveInt
    flat_modifier: int
    total: int

    @field_validator("expression")
    @classmethod
    def validate_expression(cls, value: str) -> str:
        return _canonical_text(value, field_name="dice expression")

    @field_validator("faces", "candidate_generation_indices", mode="before")
    @classmethod
    def validate_tuple_fields(cls, value: Any, info: Any) -> tuple[Any, ...]:
        return _tuple_from_wire(value, field_name=info.field_name)

    @model_validator(mode="after")
    def validate_resolution(self) -> "D20Resolution":
        if not self.faces:
            raise ValueError("a d20 resolution requires at least one generated face")
        _validate_generated_faces(self.faces, require_d20=True)

        candidates = self.candidate_generation_indices
        if not candidates:
            raise ValueError("a d20 resolution requires at least one final candidate")
        if candidates != tuple(sorted(set(candidates))):
            raise ValueError("candidate generation indices must be sorted and unique")

        by_generation = {face.generation_index: face for face in self.faces}
        if any(index not in by_generation for index in candidates):
            raise ValueError("candidate generation index must identify a generated face")
        if self.kept_generation_index not in candidates:
            raise ValueError("the kept face must be one of the final candidates")

        candidate_set = set(candidates)
        for face in self.faces:
            is_final_candidate = face.generation_index in candidate_set
            if is_final_candidate and face.status not in {"kept", "discarded"}:
                raise ValueError("final candidates must be marked kept or discarded")
            if not is_final_candidate and face.status not in {"rerolled", "replaced"}:
                raise ValueError("superseded faces must be marked rerolled or replaced")

        kept_faces = [face for face in self.faces if face.status == "kept"]
        if len(kept_faces) != 1:
            raise ValueError("a d20 resolution must have exactly one kept face")
        kept = kept_faces[0]
        if kept.generation_index != self.kept_generation_index:
            raise ValueError("kept_generation_index must identify the kept face")

        if self.mode == "normal" and len(candidates) != 1:
            raise ValueError("a normal d20 resolution must have exactly one final candidate")
        if self.mode != "normal" and len(candidates) < 2:
            raise ValueError(f"{self.mode} requires at least two final candidates")

        candidate_values = [by_generation[index].value for index in candidates]
        if self.mode == "advantage" and kept.value != max(candidate_values):
            raise ValueError("advantage must keep a highest candidate")
        if self.mode == "disadvantage" and kept.value != min(candidate_values):
            raise ValueError("disadvantage must keep a lowest candidate")
        if self.total != kept.value + self.flat_modifier:
            raise ValueError("d20 total must equal the kept face plus flat_modifier")
        return self


class D20RollFact(RollJournalModel):
    """An attack, check, or other thresholded d20 outcome."""

    kind: Literal["d20"]
    roll: D20Resolution
    threshold: int | None
    outcome: Literal["hit", "miss", "success", "failure", "none"]
    critical: bool

    @model_validator(mode="after")
    def validate_comparison(self) -> "D20RollFact":
        has_comparison = self.outcome != "none"
        if has_comparison != (self.threshold is not None):
            raise ValueError("threshold must be present exactly when an outcome is resolved")
        return self

    @property
    def total(self) -> int:
        return self.roll.total


class SavingThrowFact(RollJournalModel):
    """A saving throw with its explicit ability, DC, and authoritative outcome."""

    kind: Literal["saving_throw"]
    ability: Literal[
        "strength",
        "dexterity",
        "constitution",
        "intelligence",
        "wisdom",
        "charisma",
    ]
    roll: D20Resolution
    dc: NonNegativeInt
    succeeded: bool


class DamageAdjustment(RollJournalModel):
    """A signed change between rolled, raw, and applied damage stages."""

    stage: Literal["raw", "applied"]
    kind: Literal[
        "floor",
        "bonus",
        "reduction",
        "resistance",
        "vulnerability",
        "immunity",
        "absorption",
        "other",
    ]
    amount: int
    source_id: str | None

    @field_validator("amount")
    @classmethod
    def validate_amount(cls, value: int) -> int:
        if value == 0:
            raise ValueError("damage adjustment amount must be non-zero")
        return value

    @field_validator("source_id")
    @classmethod
    def validate_source_id(cls, value: str | None) -> str | None:
        if value is None:
            return None
        return _canonical_text(value, field_name="damage adjustment source ID")


class DamageRollFact(RollJournalModel):
    """Generated damage faces and the engine's known damage stages.

    ``applied_damage`` is explicitly ``None`` at a dice-only RNG boundary. It
    becomes an integer only when target mitigation and application have really
    completed.
    """

    kind: Literal["damage"]
    expression: str
    damage_type: str | None
    faces: tuple[DieFace, ...]
    flat_modifier: int
    rolled_total: int
    raw_damage: NonNegativeInt
    applied_damage: NonNegativeInt | None
    critical: bool
    adjustments: tuple[DamageAdjustment, ...]

    @field_validator("expression")
    @classmethod
    def validate_expression(cls, value: str) -> str:
        return _canonical_text(value, field_name="expression")

    @field_validator("damage_type")
    @classmethod
    def validate_damage_type(cls, value: str | None) -> str | None:
        if value is None:
            return None
        return _canonical_text(value, field_name="damage_type")

    @field_validator("faces", "adjustments", mode="before")
    @classmethod
    def validate_tuple_fields(cls, value: Any, info: Any) -> tuple[Any, ...]:
        return _tuple_from_wire(value, field_name=info.field_name)

    @model_validator(mode="after")
    def validate_damage(self) -> "DamageRollFact":
        _validate_generated_faces(self.faces, require_d20=False)
        kept_total = sum(face.value for face in self.faces if face.status == "kept")
        if self.rolled_total != kept_total + self.flat_modifier:
            raise ValueError("rolled_total must equal kept faces plus flat_modifier")

        raw_delta = sum(item.amount for item in self.adjustments if item.stage == "raw")
        if self.raw_damage != self.rolled_total + raw_delta:
            raise ValueError("raw_damage must equal rolled_total plus raw adjustments")
        applied_delta = sum(item.amount for item in self.adjustments if item.stage == "applied")
        if self.applied_damage is None and applied_delta:
            raise ValueError("unapplied damage must not contain applied adjustments")
        if (
            self.applied_damage is not None
            and self.applied_damage != self.raw_damage + applied_delta
        ):
            raise ValueError("applied_damage must equal raw_damage plus applied adjustments")
        return self


RollFact: TypeAlias = Annotated[
    D20RollFact | DamageRollFact | SavingThrowFact,
    Field(discriminator="kind"),
]


class RollRecordDraft(RollJournalModel):
    """Resolved engine fact before the journal assigns turn-local identity."""

    source_actor_id: str
    target_actor_id: str | None
    action_id: str
    purpose: str
    audience: RollAudienceIntent
    fact: RollFact

    @field_validator("source_actor_id", "action_id", "purpose")
    @classmethod
    def validate_required_text(cls, value: str, info: Any) -> str:
        return _canonical_text(value, field_name=info.field_name)

    @field_validator("target_actor_id")
    @classmethod
    def validate_optional_text(cls, value: str | None) -> str | None:
        if value is None:
            return None
        return _canonical_text(value, field_name="target_actor_id")


class RollRecordContext(RollJournalModel):
    """Stable actor/action metadata bound once at an engine resolution boundary."""

    source_actor_id: str
    target_actor_id: str | None
    action_id: str
    purpose: str
    audience: RollAudienceIntent

    @field_validator("source_actor_id", "action_id", "purpose")
    @classmethod
    def validate_required_text(cls, value: str, info: Any) -> str:
        return _canonical_text(value, field_name=info.field_name)

    @field_validator("target_actor_id")
    @classmethod
    def validate_optional_text(cls, value: str | None) -> str | None:
        if value is None:
            return None
        return _canonical_text(value, field_name="target_actor_id")

    def draft(self, fact: RollFact) -> RollRecordDraft:
        """Compose this metadata with one already-resolved engine fact."""

        return RollRecordDraft(
            source_actor_id=self.source_actor_id,
            target_actor_id=self.target_actor_id,
            action_id=self.action_id,
            purpose=self.purpose,
            audience=self.audience,
            fact=fact,
        )


def deterministic_roll_record_id(turn_token: str, sequence: int) -> str:
    """Return the stable identity for one turn-local journal position."""

    canonical_turn_token = _canonical_text(turn_token, field_name="turn_token")
    if isinstance(sequence, bool) or not isinstance(sequence, int) or sequence < 1:
        raise ValueError("sequence must be a positive integer")
    identity = json.dumps(
        [ROLL_RECORD_SCHEMA_VERSION, canonical_turn_token, sequence],
        allow_nan=False,
        ensure_ascii=False,
        separators=(",", ":"),
    )
    digest = hashlib.sha256(identity.encode("utf-8")).hexdigest()
    return f"roll:{digest}"


class AuthoritativeRollRecord(RollRecordDraft):
    """One canonical roll fact at a deterministic turn-local sequence."""

    schema_version: Literal[ROLL_RECORD_SCHEMA_VERSION]
    record_id: str
    turn_token: str
    sequence: PositiveInt

    @field_validator("record_id", "turn_token")
    @classmethod
    def validate_record_text(cls, value: str, info: Any) -> str:
        return _canonical_text(value, field_name=info.field_name)

    @model_validator(mode="after")
    def validate_identity(self) -> "AuthoritativeRollRecord":
        expected = deterministic_roll_record_id(self.turn_token, self.sequence)
        if self.record_id != expected:
            raise ValueError("record_id does not match turn_token and sequence")
        return self


class RollJournal(RollJournalModel):
    """A complete immutable journal for one engine turn token."""

    schema_version: Literal[ROLL_JOURNAL_SCHEMA_VERSION]
    turn_token: str
    records: tuple[AuthoritativeRollRecord, ...]

    @field_validator("turn_token")
    @classmethod
    def validate_turn_token(cls, value: str) -> str:
        return _canonical_text(value, field_name="turn_token")

    @field_validator("records", mode="before")
    @classmethod
    def validate_records_shape(cls, value: Any) -> tuple[Any, ...]:
        return _tuple_from_wire(value, field_name="records")

    @model_validator(mode="after")
    def validate_records(self) -> "RollJournal":
        for expected_sequence, record in enumerate(self.records, start=1):
            if record.sequence != expected_sequence:
                raise ValueError("roll record sequences must be contiguous and ordered from 1")
            if record.turn_token != self.turn_token:
                raise ValueError("every roll record must use the journal turn_token")
        return self

    @classmethod
    def empty(cls, turn_token: str) -> "RollJournal":
        return cls(
            schema_version=ROLL_JOURNAL_SCHEMA_VERSION,
            turn_token=turn_token,
            records=(),
        )

    def append(self, draft: RollRecordDraft) -> "RollJournal":
        """Return a new journal containing one already-resolved fact."""

        if not isinstance(draft, RollRecordDraft):
            raise TypeError("draft must be a RollRecordDraft")
        sequence = len(self.records) + 1
        record = AuthoritativeRollRecord(
            schema_version=ROLL_RECORD_SCHEMA_VERSION,
            record_id=deterministic_roll_record_id(self.turn_token, sequence),
            turn_token=self.turn_token,
            sequence=sequence,
            source_actor_id=draft.source_actor_id,
            target_actor_id=draft.target_actor_id,
            action_id=draft.action_id,
            purpose=draft.purpose,
            audience=draft.audience,
            fact=draft.fact,
        )
        return RollJournal(
            schema_version=ROLL_JOURNAL_SCHEMA_VERSION,
            turn_token=self.turn_token,
            records=(*self.records, record),
        )

    def records_after(self, sequence: int) -> tuple[AuthoritativeRollRecord, ...]:
        """Return the ordered delta after a committed turn-local sequence."""

        if isinstance(sequence, bool) or not isinstance(sequence, int):
            raise TypeError("sequence must be an integer")
        if sequence < 0 or sequence > len(self.records):
            raise ValueError("sequence must identify a journal boundary")
        return self.records[sequence:]


class EngineRollJournalRecorder:
    """Sequential engine adapter that owns the current immutable journal value.

    A recorder consumes no randomness. Rules functions supply generated faces
    after drawing them, and the recorder atomically replaces its journal with a
    validated copy containing the new fact. Constructing it from a decoded
    journal resumes at the next deterministic turn-local sequence.
    """

    def __init__(self, journal: RollJournal) -> None:
        if not isinstance(journal, RollJournal):
            raise TypeError("journal must be a RollJournal")
        self._journal = journal

    @classmethod
    def empty(cls, turn_token: str) -> "EngineRollJournalRecorder":
        return cls(RollJournal.empty(turn_token))

    @property
    def journal(self) -> RollJournal:
        return self._journal

    def bind(self, context: RollRecordContext) -> "BoundRollJournalRecorder":
        if not isinstance(context, RollRecordContext):
            raise TypeError("context must be a RollRecordContext")
        return BoundRollJournalRecorder(owner=self, context=context)

    def _append(self, draft: RollRecordDraft) -> AuthoritativeRollRecord:
        updated = self._journal.append(draft)
        record = updated.records[-1]
        self._journal = updated
        return record


class BoundRollJournalRecorder:
    """A journal recorder bound to one source, target, action, and audience."""

    def __init__(self, *, owner: EngineRollJournalRecorder, context: RollRecordContext) -> None:
        self._owner = owner
        self._context = context

    @property
    def context(self) -> RollRecordContext:
        return self._context

    def record_d20(
        self,
        *,
        expression: str,
        mode: Literal["normal", "advantage", "disadvantage"],
        generated_values: Sequence[int],
        kept_generation_index: int,
        flat_modifier: int,
        total: int,
        threshold: int | None,
        outcome: Literal["hit", "miss", "success", "failure", "none"],
        critical: bool,
    ) -> AuthoritativeRollRecord:
        """Append caller-generated d20 candidates without drawing or rerolling."""

        values = tuple(generated_values)
        if any(isinstance(value, bool) or not isinstance(value, int) for value in values):
            raise TypeError("generated d20 values must be integers")
        faces = tuple(
            DieFace(
                generation_index=index,
                sides=20,
                value=value,
                status="kept" if index == kept_generation_index else "discarded",
                replacement_generation_index=None,
            )
            for index, value in enumerate(values, start=1)
        )
        fact = D20RollFact(
            kind="d20",
            roll=D20Resolution(
                expression=expression,
                mode=mode,
                faces=faces,
                candidate_generation_indices=tuple(range(1, len(faces) + 1)),
                kept_generation_index=kept_generation_index,
                flat_modifier=flat_modifier,
                total=total,
            ),
            threshold=threshold,
            outcome=outcome,
            critical=critical,
        )
        return self._owner._append(self._context.draft(fact))

    def record_damage(
        self,
        *,
        expression: str,
        damage_type: str | None,
        die_sides: int | None,
        initial_values: Sequence[int],
        rerolls: Sequence[tuple[int, int]],
        flat_modifier: int,
        rolled_total: int,
        raw_damage: int,
        critical: bool,
        raw_adjustments: Sequence[DamageAdjustment],
    ) -> AuthoritativeRollRecord:
        """Append generated damage faces before target application is known.

        ``rerolls`` contains ``(original_generation_index, replacement_value)``
        pairs in replacement generation order. The resulting fact explicitly
        stores ``applied_damage=None``; a caller must never substitute the raw
        total for target-applied damage.
        """

        values = tuple(initial_values)
        if any(isinstance(value, bool) or not isinstance(value, int) for value in values):
            raise TypeError("generated damage values must be integers")
        replacements = tuple(rerolls)
        if any(
            not isinstance(item, tuple)
            or len(item) != 2
            or any(isinstance(value, bool) or not isinstance(value, int) for value in item)
            for item in replacements
        ):
            raise TypeError("damage rerolls must be integer index/value pairs")
        if values:
            if isinstance(die_sides, bool) or not isinstance(die_sides, int) or die_sides < 2:
                raise ValueError("die_sides must describe generated damage faces")
        elif die_sides is not None:
            raise ValueError("die_sides must be absent when no damage dice were generated")
        if replacements and not values:
            raise ValueError("static damage cannot contain rerolls")

        replacement_by_original: dict[int, tuple[int, int]] = {}
        for replacement_offset, (original_index, replacement_value) in enumerate(
            replacements, start=1
        ):
            if original_index < 1 or original_index > len(values):
                raise ValueError("damage reroll must identify an initial generated face")
            if original_index in replacement_by_original:
                raise ValueError("an initial damage face may be rerolled only once")
            replacement_generation = len(values) + replacement_offset
            replacement_by_original[original_index] = (
                replacement_generation,
                replacement_value,
            )

        faces: list[DieFace] = []
        for index, value in enumerate(values, start=1):
            replacement = replacement_by_original.get(index)
            faces.append(
                DieFace(
                    generation_index=index,
                    sides=die_sides,
                    value=value,
                    status="rerolled" if replacement is not None else "kept",
                    replacement_generation_index=(replacement[0] if replacement else None),
                )
            )
        for replacement_offset, (_original_index, replacement_value) in enumerate(
            replacements, start=1
        ):
            faces.append(
                DieFace(
                    generation_index=len(values) + replacement_offset,
                    sides=die_sides,
                    value=replacement_value,
                    status="kept",
                    replacement_generation_index=None,
                )
            )

        fact = DamageRollFact(
            kind="damage",
            expression=expression,
            damage_type=damage_type,
            faces=tuple(faces),
            flat_modifier=flat_modifier,
            rolled_total=rolled_total,
            raw_damage=raw_damage,
            applied_damage=None,
            critical=critical,
            adjustments=tuple(raw_adjustments),
        )
        return self._owner._append(self._context.draft(fact))


def _reject_duplicate_keys(pairs: Sequence[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate JSON object key '{key}'")
        result[key] = value
    return result


def _reject_json_constant(value: str) -> None:
    raise ValueError(f"unsupported JSON constant '{value}'")


def encode_roll_journal(journal: RollJournal) -> str:
    """Serialize a complete journal to canonical replay-safe JSON."""

    if not isinstance(journal, RollJournal):
        raise TypeError("journal must be a RollJournal")
    return json.dumps(
        journal.model_dump(mode="json"),
        allow_nan=False,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    )


def decode_roll_journal(payload: str | bytes) -> RollJournal:
    """Decode a complete strict journal, rejecting ambiguous JSON objects."""

    if isinstance(payload, bytes):
        payload = payload.decode("utf-8")
    if not isinstance(payload, str):
        raise TypeError("payload must be JSON text or UTF-8 bytes")
    decoded = json.loads(
        payload,
        object_pairs_hook=_reject_duplicate_keys,
        parse_constant=_reject_json_constant,
    )
    if not isinstance(decoded, dict):
        raise ValueError("roll journal JSON must be an object")
    return RollJournal.model_validate(decoded)


__all__ = [
    "ROLL_JOURNAL_SCHEMA_VERSION",
    "ROLL_RECORD_SCHEMA_VERSION",
    "AuthoritativeRollRecord",
    "BoundRollJournalRecorder",
    "D20Resolution",
    "D20RollFact",
    "DamageAdjustment",
    "DamageRollFact",
    "DieFace",
    "EngineRollJournalRecorder",
    "RollAudienceIntent",
    "RollJournal",
    "RollRecordContext",
    "RollRecordDraft",
    "SavingThrowFact",
    "decode_roll_journal",
    "deterministic_roll_record_id",
    "encode_roll_journal",
]
