"""Transport contracts and durable single-session ownership for the VTT runtime."""

from .contracts import (
    VTT_COMMAND_SCHEMA_VERSION,
    VTT_COMMIT_RESPONSE_SCHEMA_VERSION,
    VTT_EVENT_DRAFT_SCHEMA_VERSION,
    VTT_EVENT_SCHEMA_VERSION,
    VTT_PREVIEW_RESPONSE_SCHEMA_VERSION,
    VTT_VERSION_INFO_SCHEMA_VERSION,
    VTTCommand,
    VTTCommitResponse,
    VTTEvent,
    VTTEventDraft,
    VTTPreviewResponse,
    VTTResponse,
    VTTVersionInfo,
)

from .event_store import (
    EVENT_STORE_SCHEMA_VERSION,
    AppendCommitResult,
    CommandConflictError,
    EventStoreError,
    EventStoreSchemaError,
    SQLiteSessionEventStore,
    StoredCommand,
    StoredSessionSnapshot,
)
from .scene import (
    SCENE_PROJECTION_SCHEMA_VERSION,
    SCENE_SCHEMA_VERSION,
    FeetPosition,
    GridCell,
    GridPixelTransform,
    PixelPoint,
    SceneProjection,
    SceneToken,
    SquareGridScene,
    project_scene,
)
from .session_service import VTTSessionService, VTTSessionServiceError
from .solo_table import (
    SOLO_TABLE_CONTENT_VERSION,
    SOLO_TABLE_ENGINE_VERSION,
    SOLO_TABLE_MAX_ROUNDS,
    SOLO_TABLE_RULES_VERSION,
    SOLO_TABLE_SEED,
    SoloTableFixture,
    build_solo_table_fixture,
)

__all__ = [
    "EVENT_STORE_SCHEMA_VERSION",
    "VTT_COMMAND_SCHEMA_VERSION",
    "VTT_COMMIT_RESPONSE_SCHEMA_VERSION",
    "VTT_EVENT_DRAFT_SCHEMA_VERSION",
    "VTT_EVENT_SCHEMA_VERSION",
    "VTT_PREVIEW_RESPONSE_SCHEMA_VERSION",
    "VTT_VERSION_INFO_SCHEMA_VERSION",
    "AppendCommitResult",
    "CommandConflictError",
    "EventStoreError",
    "EventStoreSchemaError",
    "SQLiteSessionEventStore",
    "StoredCommand",
    "StoredSessionSnapshot",
    "SCENE_PROJECTION_SCHEMA_VERSION",
    "SCENE_SCHEMA_VERSION",
    "SOLO_TABLE_CONTENT_VERSION",
    "SOLO_TABLE_ENGINE_VERSION",
    "SOLO_TABLE_MAX_ROUNDS",
    "SOLO_TABLE_RULES_VERSION",
    "SOLO_TABLE_SEED",
    "FeetPosition",
    "GridCell",
    "GridPixelTransform",
    "PixelPoint",
    "SceneProjection",
    "SceneToken",
    "SquareGridScene",
    "SoloTableFixture",
    "VTTCommand",
    "VTTCommitResponse",
    "VTTEvent",
    "VTTEventDraft",
    "VTTPreviewResponse",
    "VTTResponse",
    "VTTSessionService",
    "VTTSessionServiceError",
    "VTTVersionInfo",
    "build_solo_table_fixture",
    "project_scene",
]
