"""Transport contracts and durable single-session ownership for the VTT runtime."""

from .contracts import (
    VTT_COMMAND_SCHEMA_VERSION,
    VTT_COMMIT_RESPONSE_SCHEMA_VERSION,
    VTT_EVENT_DRAFT_SCHEMA_VERSION,
    VTT_EVENT_SCHEMA_VERSION,
    VTT_PREVIEW_RESPONSE_SCHEMA_VERSION,
    VTT_VERSION_INFO_SCHEMA_VERSION,
    VTTCommand,
    VTTCommitResponse,
    VTTEvent,
    VTTEventDraft,
    VTTPreviewResponse,
    VTTResponse,
    VTTVersionInfo,
)

from .event_store import (
    EVENT_STORE_SCHEMA_VERSION,
    AppendCommitResult,
    CommandConflictError,
    EventStoreError,
    EventStoreSchemaError,
    SQLiteSessionEventStore,
    StoredCommand,
    StoredSessionSnapshot,
)
from .scene import (
    SCENE_PROJECTION_SCHEMA_VERSION,
    SCENE_SCHEMA_VERSION,
    FeetPosition,
    GridCell,
    GridPixelTransform,
    PixelPoint,
    SceneProjection,
    SceneToken,
    SquareGridScene,
    project_scene,
)
from .session_service import VTTSessionService, VTTSessionServiceError

__all__ = [
    "EVENT_STORE_SCHEMA_VERSION",
    "VTT_COMMAND_SCHEMA_VERSION",
    "VTT_COMMIT_RESPONSE_SCHEMA_VERSION",
    "VTT_EVENT_DRAFT_SCHEMA_VERSION",
    "VTT_EVENT_SCHEMA_VERSION",
    "VTT_PREVIEW_RESPONSE_SCHEMA_VERSION",
    "VTT_VERSION_INFO_SCHEMA_VERSION",
    "AppendCommitResult",
    "CommandConflictError",
    "EventStoreError",
    "EventStoreSchemaError",
    "SQLiteSessionEventStore",
    "StoredCommand",
    "StoredSessionSnapshot",
    "SCENE_PROJECTION_SCHEMA_VERSION",
    "SCENE_SCHEMA_VERSION",
    "FeetPosition",
    "GridCell",
    "GridPixelTransform",
    "PixelPoint",
    "SceneProjection",
    "SceneToken",
    "SquareGridScene",
    "VTTCommand",
    "VTTCommitResponse",
    "VTTEvent",
    "VTTEventDraft",
    "VTTPreviewResponse",
    "VTTResponse",
    "VTTSessionService",
    "VTTSessionServiceError",
    "VTTVersionInfo",
    "project_scene",
]
